### ISSUE TITLE
登录时奔溃

### ISSUE THREAD

**Issue by 109021017** [heipidage/GcmForMojo#22]
07-06 21:05:19.353 27187-28542/? D/GcmForMojo: 谷歌推送: {isAt=0, type=Mojo-Sys, msgId=1, title=登录事件, message=登录成功, senderType=1}
07-06 21:05:19.358 27187-28542/? I/GcmForMojo: onMessageReceived: 准备删除二维码
                                               
                                               --------- beginning of crash
07-06 21:05:19.364 27187-28542/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
                                                   Process: com.swjtu.gcmformojo, PID: 27187
                                                   java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.swjtu.gcmformojo.MessageUtil.MessageUtilDo(MessageUtil.java:466)
                                                       at com.swjtu.gcmformojo.MyFirebaseMessagingService.onMessageReceived(MyFirebaseMessagingService.java:52)
                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source:43)
                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source:96)
                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzm(Unknown Source:66)
                                                       at com.google.firebase.iid.zzb$2.run(Unknown Source:4)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                       at java.lang.Thread.run(Thread.java:764)

**Comment by milkice233** [comment]
请检查/sdcard/GcmForMojo是否有该文件夹
